### ISSUE TITLE
Get actual video frame number and time

### ISSUE THREAD

**Issue by rezgi** [defold/extension-videoplayer-mpeg#3]
**Is your feature request related to a problem? Please describe (REQUIRED):**
I need to get the ongoing decoded frame number and time in the video in order to assess if it's synced well with other game elements.

**Describe the solution you'd like (REQUIRED):**
have a getter method that returns the played frame number and time.

**Describe alternatives you've considered (REQUIRED):**
For now I'm burning the video frame number within the video itself in order to check but I need to access this data for more precise gameplay.

**Comment by britzl** [comment]
I don't see anything in the API (https://github.com/defold/extension-videoplayer-mpeg/blob/master/mpeg/src/pl_mpeg.h) to return the frame number. You can get the current time, and perhaps from that make some kind of assumption about frame number (if you know the frame rate)

**Comment by rezgi** [comment]
> I don't see anything in the API (https://github.com/defold/extension-videoplayer-mpeg/blob/master/mpeg/src/pl_mpeg.h) to return the frame number. You can get the current time, and perhaps from that make some kind of assumption about frame number (if you know the frame rate)
> 
> ```lua
> print(mpeg.get_info().time) -- seconds (number)
> ```

Getting the current time is more than enough, converting to framerate won't be a problem. Is that time() getter new or did I miss it? Didn't read it in the api file. Thanks
